apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169960432
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169960432
    app.kubernetes.io/part-of: test-app-169960432
  name: java-quarkus-169960432
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169960432
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169960432
    spec:
      containers:
      - image: quay.io/hacdev/7ni2sabr-tenant/test-app-169960432/java-quarkus-169960432@sha256:bb00737789e79ec5b9631900708e0333dc511b91747939a44d88258a6b28925e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
